# Install dependencies only when needed
FROM node:16 AS deps

ARG node_env=production
ENV NODE_ENV ${node_env}

WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn install --silent

COPY . .

# RUN yarn install --silent
ENTRYPOINT ["yarn", "dev"]

